name: ci  
on:  
  push:
  pull_request:
    branches:
      - main
jobs:  
  build:  
    runs-on: ubuntu-latest  
    strategy:  
      fail-fast: false  
      matrix:  
        python-version: ["3.12"]  
    steps:  
    - uses: actions/checkout@v4  
    - name: Set up Python ${{ matrix.python-version }}  
      uses: actions/setup-python@v4  
      with:  
        python-version: ${{ matrix.python-version }} 
    - name: Install poetry
      uses: abatilo/actions-poetry@v2
    - uses: actions/cache@v3
      name: Define a cache for the virtual environment based on the dependencies lock file
      with:
        path: ./.venv
        key: venv-${{ hashFiles('poetry.lock') }}
    - name: Install project dependencies
      run: poetry install
    - name: Run lint
      run: poetry run ruff format --line-length 100 .
    - name: Run tests
      run: poetry run pytest -v --cov=.
